apiVersion: v1
kind: Service
metadata:
  name: iris-api-service
spec:
  type: LoadBalancer
  selector:
    app: iris-api
  ports:
    - protocol: TCP
      port: 80         # External port (accessible via curl)
      targetPort: 8200 # Internal container port
